### PR TITLE
Added Kokscraft.pl, Rapy.pl, Some polish servers

### PR DESCRIPTION
**Pull request by vanishLLC**
Kokscraft.pl Is the largest minigame focused server in poland with around 5k players at one time

### CODE REVIEW

**Review by amplitudesxd — CHANGES_REQUESTED** [review]
File must end in .json

**Comment by vanishLLC** [comment]
Oh yeah i see fixed!

**Review by amplitudesxd — APPROVED** [review]

**Review by amplitudesxd — CHANGES_REQUESTED** [review]
Hosts should be all lowercase ("craftplay.pl")

**Review by amplitudesxd — CHANGES_REQUESTED** [review]
Hosts should be lowercase ("rapy.pl")

**Comment by vanishLLC** [comment]
Fixed

**Review by amplitudesxd — APPROVED** [review]
LGTM

**Pull request merged**
